### ISSUE TITLE
表单选项中如何控制显示当前登陆者的部门及子部门

### ISSUE THREAD

**Issue by lameroy** [steedos/steedos-project-ruihui#27]
filtersFunction方法如何取到当前登陆者的信息： user/userSession/organizations
根据用户信息做部门筛选：只显示当前登陆者的部门及子部门

<img width="1583" alt="image" src="https://user-images.githubusercontent.com/54792412/167366822-4a2ca378-e116-4cef-a0c0-74fe979af3eb.png">

![image](https://user-images.githubusercontent.com/54792412/167367411-f25e58cf-d376-47eb-9ad5-f38559615424.png)

**Comment by yinlianghui** [comment]
filtersFunction内容写成`return ["users", "in", [Steedos.userId()]]`试下。
或者 `filters: [["users", "in", "{userId}"]]`应该也是可以的，不用写函数。

**Comment by lameroy** [comment]
子部门没显示

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/54792412/167377669-64c0a4a4-9bf2-4ded-b4b9-16de1dfdbab4.png">

**Comment by yinlianghui** [comment]
希望这个弹出窗口返回的是以下哪种方案：
1.当前登录用户所属的本部门及其子部门
2.当前登录用户所属的所有部门及其子部门

方案1：
```
var orgId = Creator.USER_CONTEXT.user.organization._id;
return [["_id", "in", [orgId], "or",["parents","in",[orgId]]]]
```

方案2：
```
var orgIds = Creator.USER_CONTEXT.user.organizations.map((item)=>{return item._id});
return [["_id", "in", orgIds, "or",["parents","in",orgIds]]];
```

**Comment by lameroy** [comment]
return 如下是正确的（前面条件也需加中括号：["_id","in",orgIds]）：

 return [[["_id", "in", orgIds], "or",["parents","in",orgIds]]];
