### ISSUE TITLE
网页端更新权限集后，自定义请求获取的req.user.roles（用户的权限）没有被更新，需要重启项目才能获取到更新的值

### ISSUE THREAD

**Issue by wangxiang3** [steedos/steedos-project-ruihui#40]

**Comment by wangxiang3** [comment]
链接: https://pan.baidu.com/s/1_8UZqSV1KKbTH4mUItPjkA 提取码: j0wm 
视频地址

**Comment by wangxiang3** [comment]
![截屏2022-06-16 下午2 36 05](https://user-images.githubusercontent.com/72076955/174007068-fc448b0a-d8c4-4e7c-8a0f-9cfe29e1204e.png)

**Comment by yinlianghui** [comment]
不是bug，用户的信息，即userSession有10分钟缓存。
