### ISSUE TITLE
页面布局里面按钮显示条件公式如何写

### ISSUE THREAD

**Issue by lameroy** [steedos/steedos-project-ruihui#42]
根据简档/权限集 控制按钮的显示隐藏，如下公式不生效

<img width="1689" alt="image" src="https://user-images.githubusercontent.com/54792412/176102499-59149369-f487-49d3-8f6e-7e7cf71a05c6.png">

**Comment by yinlianghui** [comment]
见：https://github.com/steedos/steedos-platform/issues/3340
待发版本。
